language: php

env:
  - SH=bash

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/simple-phpunit -v

notifications:
    on_success: never
    on_failure: always
